### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by jnalley** [hortonworks/cb-cli#179]
Hi,

The `cb` command produces no output when running commands.

For example, the following commands produce no output (and no error):

```
cb cluster list
cb blueprint list
```

When run with `--debug` I get the following:

```
cb --debug cluster list
INFO:  [ReadConfig] found config file: /home/user/.cb/config
INFO:  [ReadConfig] selected profile: default
INFO:  [ConfigRead] Config read from file, setting as global variable:
username: foo@bar.com
password: '*'
server: https://10.123.123.1
output: table

DEBUG: Request POST https://10.123.123.1/identity/oauth/authorize?response_type=token&client_id=cloudbreak_shell
DEBUG: Response method:POST status:302 duration:613ms req_url:https://10.123.123.1/identity/oauth/authorize?response_type=token&client_id=cloudbreak_shell
INFO:  [listStacksImpl] sending stack list request
DEBUG: Request GET https://10.123.123.1/cb/api/v1/stacks/account
DEBUG: Response method:GET status:200 duration:1115ms req_url:https://10.123.123.1/cb/api/v1/stacks/account
INFO:  list stacks took 2.24821799s
```

I configured an intercept proxy in order to view the HTTP response and confirmed that valid JSON (containing the requested data) is returned from the server, but no output is printed by the `cb` command.

cb version 2.4.0-dev.18-2018-01-08T19:50:56
cloudbreak server: Version: 1.16.4

I get the same result on both Mac and Linux.

Thanks!

**Comment by mhmxs** [comment]
Hi @jnalley ,

Did you try any other output format than table?

**Comment by mhmxs** [comment]
For Cloudbreak 1.16.4 you have to use Cloudbreak shell instead of cb. With the version upgrade we broke API compatibility.

**Comment by jnalley** [comment]
Thanks for the info!
