### ISSUE TITLE
Cloudbreak CLI 2.7.0 Binaries No Longer Available

### ISSUE THREAD

**Issue by ronso-rage** [hortonworks/cb-cli#737]
The binaries for previous versions of 2.7.0 are no longer available on S3.
https://s3-us-west-2.amazonaws.com/cb-cli/cb-cli_2.7.0-dev.36-446-g775eb56_Darwin_x86_64.tgz

Is there a way to source these binaries again or is there any docs on how to build them?

**Comment by pdarvasi** [comment]
Hey @ronso-rage!
Now we have the released versions there e.g.:https://s3-us-west-2.amazonaws.com/cb-cli/cb-cli_2.7.0_Darwin_x86_64.tgz.

Do you really need to build a dev version? If so you can do that with `"make build-darwin"`

**Comment by ronso-rage** [comment]
The new released version suffices. Thank you!
